@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Feb 09 20:44:10 +0330 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim average_tb_behav -key {Behavioral:sim_1:Functional:average_tb} -tclbatch average_tb.tcl -view C:/Users/Maede/Desktop/FPGA_Final_project_Ghassab_Alizadeh/section2_fpga_final_ptoject/average_edge_filter/average_tb_behav.wcfg -log simulate.log"
call xsim  average_tb_behav -key {Behavioral:sim_1:Functional:average_tb} -tclbatch average_tb.tcl -view C:/Users/Maede/Desktop/FPGA_Final_project_Ghassab_Alizadeh/section2_fpga_final_ptoject/average_edge_filter/average_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
